<?php
    namespace Config;
/**
 * Generated by framework installer - Wed, 30 Oct 2019 22:08:41 +0000
*/
    class Config
    {
        const BASEDNAME	= '/projects/csc3123';
        const PUTORPATCH	= 'PATCH';
        const SESSIONNAME	= 'PSIcsc3123';
        const DBTYPE	= 'mysql';
        const DBHOST	= 'localhost';
        const DB	= 'db';
        const DBUSER	= 'user';
        const DBPW	= 'secret';
        const SITENAME	= 'csc3123';
        const SITENOREPLY	= 'noreply@chester-lloyd.dev';
        const SYSADMIN	= 'admin@chester-lloyd.dev';
        const DBRX	= FALSE;
        const REGISTER	= TRUE;
        const UPUBLIC	= FALSE;
        const UPRIVATE	= TRUE;
        const USEPHPM	= FALSE;

        public static function setup()
        {
            \Framework\Web\Web::getinstance()->addheader([
            'Date'                   => gmstrftime('%b %d %Y %H:%M:%S', time()),
            'Window-Target'          => '_top',      # deframes things
            'X-Frame-Options'	     => 'DENY',      # deframes things: SAMEORIGIN would allow this site to use frames
            'Content-Language'	     => 'en',
            'Vary'                   => 'Accept-Encoding',
            'X-Content-Type-Options' => 'nosniff',
            'X-XSS-Protection'       => '1; mode=block',
            'Strict-Transport-Security' => 'max-age=31536000', // enforces HTTPS for this domain for a year
            ]);
        }


        public static $defaultCSP = [
                'default-src' => ["'self'"],
                'font-src' => ["'self'", "data:", "*.fontawesome.com"],
                'img-src' => ["'self'", "data:"],
                'script-src' => ["'self'", "stackpath.bootstrapcdn.com", "cdnjs.cloudflare.com", "code.jquery.com"],
                'style-src' => ["'self'", "*.fontawesome.com", "stackpath.bootstrapcdn.com"],
        ];
    }

?>
